name: Hello world workflow
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello world!"
        shell: bash
  hi:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hi!"
        shell: bash
  goodbye:
    runs-on: ubuntu-22.04
    steps:
      - name: goodbye world
        run: echo "Goodbye world!"
        shell: bash
